# Generated by Django 3.1.3 on 2021-06-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0002_auto_20210507_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapes',
            name='down',
            field=models.FloatField(default=0.3555, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shapes',
            name='left',
            field=models.FloatField(default=0.6555, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shapes',
            name='right',
            field=models.FloatField(default=3.755, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shapes',
            name='up',
            field=models.FloatField(default=4.588, max_length=16),
            preserve_default=False,
        ),
    ]
