# Generated by Django 3.2.5 on 2021-08-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0004_shapes_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapes',
            name='area',
            field=models.FloatField(default='0.0', max_length=16),
        ),
        migrations.AddField(
            model_name='shapes',
            name='id_after_checked',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='shapes',
            name='if_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shapes',
            name='uploader',
            field=models.CharField(default='', max_length=10),
        ),
    ]
