# Generated by Django 3.2.5 on 2021-08-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0005_auto_20210812_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapes',
            name='update_time',
            field=models.CharField(default='0', max_length=16),
        ),
    ]
